# .github/workflows/azure-dotnet-sonarcloud.yml

name: Build, Analyze with SonarCloud, Deploy to Azure

on:
  push:
    branches:
      - master
  pull_request:

env:
  AZURE_WEBAPP_NAME: your-app-service-name        # Set your Azure Web App name
  DOTNET_VERSION: '9.0.x'                          # or 7.0.x, 6.0.x
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}           # SonarCloud token in GitHub secrets
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }} # Azure service principal credentials (JSON)

jobs:
  build_analyze_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}


    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the app
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
